[project]
name = "sihproject"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
 "fastapi",
    "uvicorn",
    "motor",
    "python-dotenv",
    "requests",
    "numpy",
    "pandas",
    "google-auth",
    "scikit-learn"
   "pymongo",
  "pydantic",
"email-validator",
"bcrypt",
"python-multipart",
"requests",
"joblib",
"websockets",
"httpx"
    
]

[tool.vercel]
entrypoint = "backend.app.main:app"
